version: "3.9"
services:
  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./sqlitedata:/root/db/
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    networks:
      - my_network
    restart: unless-stopped
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jupyter_files:/home/jovyan
    ports:  
      - "8888:8888"
    networks:
      - my_network
  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: "jupyterdb"
      POSTGRES_USER: "jupyterdb_user"
      POSTGRES_PASSWORD: "jupyterdb_user_123"
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
networks:
  my_network:
      driver: bridge
volumes:
  pgdata:
  sqlitedata: